### ISSUE TITLE
Swisscom tv air 2.0

### ISSUE THREAD

**Issue by bladerunner82** [kungpfui/plugin.video.swisscom_tv_unofficial#2]
Hallo thanks for that addon
Is it possible to Update or to write a new One for the much better Version Air 2.0 
All the Features in this swisscom app (swisscom tv air 2.0)are great ,it would be nice to use them in kodi
The new Features are replay function 30h ,recordings,and u can use it also as a free User
With your Facebook Account.

Thanks in Advanced

**Comment by kungpfui** [comment]
Well, I am not related to Swisscom. So all of my knowledge is based on reverse engineering or trial and error. That's a time consuming task which I don't spend when I'm not interested in something.
That's my first and only Kodi plugin and I'm happy with it. This here is Github, so everybody can improve the work of others.

Ok, I have thrown an eye on TV Air 2.0 and the website is still in beta stage. Personally I wouldn't spend to much time in analyzing there website because it can change all of a sudden and the work starts again.

**Comment by bladerunner82** [comment]
Ok thanks i can understand it from ur point of view

Schöne grüsse in die Schweiz
