### ISSUE TITLE
Server List

### ISSUE THREAD

**Issue by NowyQuei** [kungpfui/plugin.video.swisscom_tv_unofficial#3]
Hi
short question i am working an unofficial app too, can you give an hint where you have found the IPs and details about the connection?

**Comment by nliaudat** [comment]
Try https://github.com/iptv-ch/iptv-ch.github.io

**Comment by kungpfui** [comment]
In the past the way to go was to add a Raspberry Pi configured as Ethernet switch in front of the TV box and switch all channels through by hand. I've logged then the connection details by "iftop -P". Also try 'n' error helped a lot because the IP and port range used by Swisscom and other IP broadcasters is very limited.
